-- AlterEnum
ALTER TYPE "ActivityAction" ADD VALUE 'COMMENT_ADDED';
ALTER TYPE "ActivityAction" ADD VALUE 'COMMENT_REMOVED';
ALTER TYPE "ActivityAction" ADD VALUE 'MEETING_NOTE_ADDED';
ALTER TYPE "ActivityAction" ADD VALUE 'MEETING_NOTE_UPDATED';
ALTER TYPE "ActivityAction" ADD VALUE 'MEETING_NOTE_REMOVED';
