// One-time import dataset, transcribed from the Notion "Marketing
// Communications & PR Calendar" CSV export the user provided. Two fully
// blank rows in the source (no name, no other data) were dropped.
export type MarcomCalendarRow = {
  name: string
  notionType: string | null
  notionStatus: "Planning" | "Scheduled" | "In Progress" | "Completed"
  startDate: string | null
  endDate: string | null
  notionPriority: "High" | "Low" | null
  targetAudience: string | null
  channel: string | null
}

export const MARCOM_CALENDAR_ROWS: MarcomCalendarRow[] = [
  {
    name: "Introduction Ppt v01r01",
    notionType: "Marketing Materials",
    notionStatus: "In Progress",
    startDate: "2026-04-27",
    endDate: "2026-05-31",
    notionPriority: "High",
    targetAudience: "Customers, Internal Team",
    channel: "Email",
  },
  {
    name: "Dragon Boat E-Card Distribution",
    notionType: "E-Card",
    notionStatus: "Completed",
    startDate: "2026-06-08",
    endDate: "2026-06-15",
    notionPriority: "Low",
    targetAudience: "Internal Team",
    channel: "Email",
  },
  {
    name: "E-Newsletter Issue #7",
    notionType: "E-Newsletter",
    notionStatus: "In Progress",
    startDate: "2026-04-20",
    endDate: "2026-05-29",
    notionPriority: "High",
    targetAudience: "Industry Professionals, Media, Prospects",
    channel: "Email, Website",
  },
  {
    name: "Dragon Boat Social Media Post",
    notionType: "Social Media Post",
    notionStatus: "Planning",
    startDate: "2026-06-10",
    endDate: "2026-06-17",
    notionPriority: null,
    targetAudience: null,
    channel: "Facebook, WeChat",
  },
  {
    name: "OneSong Concert",
    notionType: "Event",
    notionStatus: "Planning",
    startDate: "2026-07-11",
    endDate: null,
    notionPriority: null,
    targetAudience: null,
    channel: "Facebook",
  },
  {
    name: "OneSong Concert Recap",
    notionType: "Press Release, Social Media Post",
    notionStatus: "Planning",
    startDate: "2026-07-11",
    endDate: "2026-07-13",
    notionPriority: null,
    targetAudience: null,
    channel: null,
  },
  {
    name: "Red Dot Announcement",
    notionType: "Press Release, Social Media Post",
    notionStatus: "Completed",
    startDate: "2026-05-04",
    endDate: "2026-05-21",
    notionPriority: null,
    targetAudience: null,
    channel: "Facebook, Website",
  },
  {
    name: "2026 Japan Label Forum",
    notionType: "Event",
    notionStatus: "Planning",
    startDate: "2026-10-14",
    endDate: null,
    notionPriority: null,
    targetAudience: null,
    channel: null,
  },
  {
    name: "World Label Awards",
    notionType: "Press Release, Social Media Post",
    notionStatus: "Completed",
    startDate: "2026-05-05",
    endDate: "2026-05-25",
    notionPriority: null,
    targetAudience: null,
    channel: null,
  },
  {
    name: "中秋節 E-card",
    notionType: "Social Media Post",
    notionStatus: "Planning",
    startDate: "2026-09-25",
    endDate: null,
    notionPriority: null,
    targetAudience: null,
    channel: null,
  },
  {
    name: "中秋節 Activity (?)",
    notionType: "Social Media Post",
    notionStatus: "Planning",
    startDate: null,
    endDate: null,
    notionPriority: null,
    targetAudience: null,
    channel: null,
  },
  {
    name: "至真至美獎",
    notionType: "Event",
    notionStatus: "Planning",
    startDate: "2026-08-21",
    endDate: null,
    notionPriority: null,
    targetAudience: null,
    channel: null,
  },
  {
    name: "E-Newsletter",
    notionType: null,
    notionStatus: "Planning",
    startDate: null,
    endDate: null,
    notionPriority: null,
    targetAudience: null,
    channel: null,
  },
  {
    name: "中秋節 E-Card Distribution",
    notionType: "E-Card",
    notionStatus: "Planning",
    startDate: "2026-09-14",
    endDate: "2026-09-21",
    notionPriority: null,
    targetAudience: null,
    channel: null,
  },
  {
    name: "Christmas Card",
    notionType: "Social Media Post",
    notionStatus: "Planning",
    startDate: "2026-12-24",
    endDate: null,
    notionPriority: null,
    targetAudience: null,
    channel: null,
  },
  {
    name: "Taiwan Global Angels Visit",
    notionType: "Event",
    notionStatus: "Planning",
    startDate: "2026-09-18",
    endDate: null,
    notionPriority: null,
    targetAudience: null,
    channel: null,
  },
  {
    name: "Taiwan Global Angels Visit Recap Post",
    notionType: "Social Media Post",
    notionStatus: "Planning",
    startDate: "2026-09-15",
    endDate: "2026-09-21",
    notionPriority: null,
    targetAudience: "Customers, General Public",
    channel: "Facebook",
  },
  {
    name: "CZJ Open House",
    notionType: "Event, Social Media Post",
    notionStatus: "Completed",
    startDate: "2026-05-21",
    endDate: "2026-05-28",
    notionPriority: null,
    targetAudience: null,
    channel: null,
  },
  {
    name: "AI Taiwan Exhibition",
    notionType: "Event",
    notionStatus: "Planning",
    startDate: "2026-06-23",
    endDate: "2026-06-25",
    notionPriority: null,
    targetAudience: null,
    channel: null,
  },
  {
    name: "Red Dot Award Ceremony",
    notionType: "Event",
    notionStatus: "Scheduled",
    startDate: "2026-07-05",
    endDate: "2026-07-09",
    notionPriority: null,
    targetAudience: null,
    channel: null,
  },
]
